codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%
  ignore:
    - 'pymare/tests/'
    - 'pymare/_version.py'
    - 'pymare/info.py'
